/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as PdfToImagesRouteImport } from './routes/pdf-to-images'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as RearrangeRouteImport } from './routes/rearrange'
import { Route as SplitRouteImport } from './routes/split'
import { Route as StampRouteImport } from './routes/stamp'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImagesRoute = PdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const RearrangeRoute = RearrangeRouteImport.update({
  id: '/rearrange',
  path: '/rearrange',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const StampRoute = StampRouteImport.update({
  id: '/stamp',
  path: '/stamp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/protect': typeof ProtectRoute
  '/rearrange': typeof RearrangeRoute
  '/split': typeof SplitRoute
  '/stamp': typeof StampRoute
  '/unlock': typeof UnlockRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/protect': typeof ProtectRoute
  '/rearrange': typeof RearrangeRoute
  '/split': typeof SplitRoute
  '/stamp': typeof StampRoute
  '/unlock': typeof UnlockRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/protect': typeof ProtectRoute
  '/rearrange': typeof RearrangeRoute
  '/split': typeof SplitRoute
  '/stamp': typeof StampRoute
  '/unlock': typeof UnlockRoute
  '/word-to-pdf': typeof WordToPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/images-to-pdf'
    | '/merge'
    | '/pdf-to-images'
    | '/privacy'
    | '/protect'
    | '/rearrange'
    | '/split'
    | '/stamp'
    | '/unlock'
    | '/word-to-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/images-to-pdf'
    | '/merge'
    | '/pdf-to-images'
    | '/privacy'
    | '/protect'
    | '/rearrange'
    | '/split'
    | '/stamp'
    | '/unlock'
    | '/word-to-pdf'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/images-to-pdf'
    | '/merge'
    | '/pdf-to-images'
    | '/privacy'
    | '/protect'
    | '/rearrange'
    | '/split'
    | '/stamp'
    | '/unlock'
    | '/word-to-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  MergeRoute: typeof MergeRoute
  PdfToImagesRoute: typeof PdfToImagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectRoute: typeof ProtectRoute
  RearrangeRoute: typeof RearrangeRoute
  SplitRoute: typeof SplitRoute
  StampRoute: typeof StampRoute
  UnlockRoute: typeof UnlockRoute
  WordToPdfRoute: typeof WordToPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-images': {
      id: '/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/pdf-to-images'
      preLoaderRoute: typeof PdfToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rearrange': {
      id: '/rearrange'
      path: '/rearrange'
      fullPath: '/rearrange'
      preLoaderRoute: typeof RearrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamp': {
      id: '/stamp'
      path: '/stamp'
      fullPath: '/stamp'
      preLoaderRoute: typeof StampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  MergeRoute: MergeRoute,
  PdfToImagesRoute: PdfToImagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectRoute: ProtectRoute,
  RearrangeRoute: RearrangeRoute,
  SplitRoute: SplitRoute,
  StampRoute: StampRoute,
  UnlockRoute: UnlockRoute,
  WordToPdfRoute: WordToPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
